name: Build console app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-build-dotnet:
    name: Build dotnet app
    uses: ./.github/workflows/buildDotNetConsoleApp.yml
  call-build-native:
    name: Build native app
    uses: ./.github/workflows/buildNativeConsoleApp.yml