name: Run performance tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      target_branch:
        type: string
        required: true

jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.target_branch }}
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Run .net performance tests
      run:  dotnet run --project performance/performance.csproj -c Release --nologo
    - name: Send Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: benchmark-results@${{ github.event.inputs.target_branch }}
        path: |
          ./performance/BenchmarkDotNet.Artifacts/results
