name: Run tests

on:
  workflow_call

jobs:
  Run-tests:
    runs-on: ubuntu-latest  #https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Install extend nuget package
      run: nuget install extent -Version 0.0.3
    - name: show
      run: |
        cd extent.0.0.3/tools
        ls
        cd ..
    - name: Run .net tests
      run: dotnet test tests/tests.csproj --nologo --results-directory "results" --logger "trx;logfilename=nunit.xml"
      continue-on-error: true
    - name: Convert results to html
      run: extent.0.0.3/tools/extent -i results/nunit.xml -o results/
    - name: Send Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: nunit-results
        path: |
          ./results/